-- Execute in the Supabase SQL Editor before the production rollout.
-- This migration is intentionally idempotent where PostgreSQL permits it.

-- Every Supabase Auth user needs a profile row for /auth/me and subscription state.
-- The existing user_profiles table must provide defaults for its non-null premium fields.
-- Keep the project's existing function and trigger names so only one trigger runs.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.user_profiles (id, email)
  values (new.id, coalesce(new.email, ''))
  on conflict (id) do update
    set email = excluded.email;

  return new;
end;
$$;

-- Remove the name used by a pre-release version of this migration, if present.
drop trigger if exists on_auth_user_created_spectrum on auth.users;
drop trigger if exists trg_on_auth_user_created on auth.users;
create trigger trg_on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- The application checks purchase ownership before insertion. This database
-- constraint closes the race between two concurrent attempts with one receipt.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'redeemed_purchases_external_id_unique'
      and conrelid = 'public.redeemed_purchases'::regclass
  ) then
    alter table public.redeemed_purchases
      add constraint redeemed_purchases_external_id_unique unique (external_id);
  end if;
end;
$$;

-- Used by POST /notifications/token and the push delivery worker.
create table if not exists public.device_push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  expo_push_token text not null,
  platform text not null check (platform in ('ios', 'android')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint device_push_tokens_user_token_unique unique (user_id, expo_push_token)
);

-- Direct clients cannot read or alter device tokens. The API and worker use
-- the server-only service role, which bypasses RLS after validating the user.
alter table public.device_push_tokens enable row level security;

create unique index if not exists device_push_tokens_user_token_unique
  on public.device_push_tokens (user_id, expo_push_token);

-- Confirm in the Supabase dashboard that RLS remains enabled on all three
-- public tables and that only the API's service role bypasses its policies.
