-- Enforces delivery caps for the coverage digest and stores one community vote
-- per authenticated user for each official source shown on a topic.

create table if not exists public.push_digest_deliveries (
  id bigint generated by default as identity primary key,
  delivery_date date not null,
  delivery_slot text not null check (delivery_slot in ('morning', 'evening')),
  topic_id uuid not null references public.topics (id) on delete cascade,
  dedup_key text not null unique,
  status text not null default 'pending' check (status in ('pending', 'sent', 'failed', 'skipped')),
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  error_message text,
  constraint push_digest_deliveries_date_slot_unique unique (delivery_date, delivery_slot)
);

alter table public.push_digest_deliveries enable row level security;

create index if not exists push_digest_deliveries_topic_id_idx
  on public.push_digest_deliveries (topic_id, created_at desc);

create index if not exists device_push_tokens_active_idx
  on public.device_push_tokens (expo_push_token)
  where is_active = true;

create table if not exists public.official_source_votes (
  topic_id uuid not null references public.topics (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  vote text not null check (vote in ('accurate', 'inaccurate')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (topic_id, user_id)
);

alter table public.official_source_votes enable row level security;

create index if not exists official_source_votes_topic_vote_idx
  on public.official_source_votes (topic_id, vote);

notify pgrst, 'reload schema';
